1. Adding two matrices 

Addition is one of the easiest operation to carry out. The same hold true for matrices. Two matrices can be added only if they have the same dimensions. The elements at similar positions get added.

Given two matrices A and B having (n1 x m1) and (n2 x m2) dimensions respectively. Add A and B. 

Example 1:

Input:
n1 = 2, m1 = 3
A[][] = {{1, 2, 3},
         {4, 5, 6}}

n2 = 2, m2 = 3
B[][] = {{1, 3, 3},
         {2, 3, 3}}

Output: 2 5 6 6 8 9
Explanation:
The summation matrix of A and B is:
res[][] = {{2, 5, 6},
           {6, 8, 9}}
The output is generated by traversing each
row sequentially.



class Solution{
    static int[][] sumMatrix(int A[][], int B[][])
    {
       // code here
       int n1=A.length;
       int m1=A[0].length;
       int n2=B.length;
       int m2=B[0].length;
       
       int res[][]=new int[n1][m1];
       int empty[][]=new int[0][0];//empty array if dimensions are not same
       
       if((n1!=n2)||(m1!=m2))
       {
           return empty;
       }
       for(int i=0;i<n1;i++)
        for(int j=0;j<m1;j++)
            res[i][j]=A[i][j]+B[i][j];
       
       return res;
    }
}
Expected Time Complexity: O(n1 * m1)
Expected Auxiliary Space: O(n1 * m1) for the resultant matrix only. 